@host = http://localhost:3000

### Login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "usuario@pollocentro.com",
  "password": "<contraseña-segura>"
}

### Inventory
GET {{host}}/api/inventory

### Suppliers
GET {{host}}/api/suppliers
